####################################################################################
# Makefile (configuration file for GNU make - see http://www.gnu.org/software/make/)
#
# --------------------------------------------------------------------------------
# This is a generic makefile in the sense that it doesn't require to be 
# modified when adding/removing new source files.
# --------------------------------------------------------------------------------
#
# Author: Sebastien Varrette <Sebastien.Varrette@uni.lu>
#          Web page : http://www-id.imag.fr/~svarrett/
# Version : 1.2
# Creation date : 2012-07-24
#
# Please refer to ../Makefile for more informations on compilation options
# Alternatively, you may try 'make help'
# 
all:
	$(MAKE) -C ../

%:
	$(MAKE) -C ../ $@

